#!/usr/bin/env python3

import asyncio
from functools import partial
from signal import SIGINT, SIGTERM

ROOM_NAMES = ['room1', 'room2']


def signal_handler(chatango_bot):
    chatango_bot.disconnect()


from chatangobot.core.manager import Manager

loop = asyncio.get_event_loop()
try:
    bot = Manager(loop=loop, pm=True)

    loop.add_signal_handler(SIGINT, partial(signal_handler, bot))
    loop.add_signal_handler(SIGTERM, partial(signal_handler, bot))

    loop.run_until_complete(bot.connect(*ROOM_NAMES)

    # Wait all tasks
    loop.run_until_complete(asyncio.gather(*asyncio.Task.all_tasks()))
finally:
    loop.close()
